### ISSUE TITLE
Dialogue!!!!

### ISSUE THREAD

**Issue by tmkoth431** [tmkoth431/textgame#3]
Need dialogue, must include:
- npc's that give quests
- dialogue that allows learning of lore

**Comment by TrollBlox** [comment]
should I do it like text adventure game where you put the npc object in the room object and the npc object has a bunch of array lists and like those array lists have like item object and all that is but up of strings

**Comment by tmkoth431** [comment]
> should I do it like text adventure game where you put the npc object in the room object and the npc object has a bunch of array lists and like those array lists have like item object and all that is but up of strings

Yes, there should be a list of npcs in each town and they should all have possible string responses

**Comment by TrollBlox** [comment]
don't seem too hard but. gonna have to learn how your game even works first lol

**Comment by TrollBlox** [comment]
is there only one npc max per map tile or can there be multiple?

**Comment by TrollBlox** [comment]
bro it wasn't done I'm pretty sure
